#!/bin/sh -e

action="$1"
oldversion="$2"

if [ "$action" != configure ]
then
	exit 0
fi

setup_aptmirror_user() {
        if ! id apt-mirror > /dev/null 2>&1 ; then
    		adduser --quiet --system --group --no-create-home --home /var/spool/apt-mirror --shell /bin/sh apt-mirror
	fi
}

set_aptmirror_owner() {
	chown apt-mirror:apt-mirror /var/spool/apt-mirror
	chown apt-mirror:apt-mirror /var/spool/apt-mirror/mirror
	chown apt-mirror:apt-mirror /var/spool/apt-mirror/skel
	chown apt-mirror:apt-mirror /var/spool/apt-mirror/var
}

setup_aptmirror_user
set_aptmirror_owner

# Automatically added by dh_installdocs
if [ "$1" = "configure" ]; then
        if [ -d /usr/doc -a ! -e /usr/doc/apt-mirror -a -d /usr/share/doc/apt-mirror ]; then
                ln -sf ../share/doc/apt-mirror /usr/doc/apt-mirror
        fi
fi
# End automatically added section
